jsonToImg/urls.py
from django.contrib import admin
from django.urls import path
from startapp import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.check),

]

startapp/models.py
from django.db import models

# Create your models here.

startapp/views.py
from django.shortcuts import render, HttpResponse
from django import forms
import json

# Create your views here.

from graphviz import Digraph


def json_to_image(data=None):
    u = Digraph('unix', format='png',
                node_attr={'color': 'lightblue2', 'style': 'filled'},
                engine='dot')
    colors = {"int": '#d25f76',
              "float": 'orange',
              "list": '#6c42c1',
              "dict": '#ae8f65',
              "str": '#96abff'}

    def get_type(var):
        return type(var).__name__

    def get_edges(treedict, parent=None, Clabel=None):
        for key in treedict.keys():
            # key_type = type(treedict[key])
            if parent:
                u.edge(parent, key, label=get_type(treedict[key]) ,fontcolor=colors[get_type(treedict[key])], color=colors[get_type(treedict[key])])
            if type(treedict[key]) not in [dict, list]:
                pass
                # u.edge(key,get_type(treedict[key]),label=get_type(treedict[key]))
            elif type(treedict[key]) is dict:
                # u.node(key)
                get_edges(treedict[key], parent=key,
                          Clabel=get_type(treedict[key]))
            elif type(treedict[key]) is list:
                # u.edge(parent,key,label="list")
                for i in treedict[key][:1]:
                    if type(i) not in [str, int, float]:
                        get_edges(i, parent=key, Clabel=get_type(i))
                    else:
                        u.edge(key, get_type(i), label=get_type(
                            i),fontcolor=colors[get_type(i)], color=colors[get_type(i)])

    if type(data) is list:
        for i, x in enumerate(data):
            if i < 1:
                get_edges(x,"List")
    elif type(data) is dict:
        main_ = "Response"
        u.node(main_)
        with u.subgraph() as s:
            s.attr(rank="same")
            for i in data.keys():
                s.node(i)
                s.edge(main_, i, label=get_type(data[i]), fontcolor=colors[get_type(data[i])],color=colors[get_type(data[i])])
        get_edges(data)
    return u.pipe()


class front_end(forms.Form):
    response = forms.JSONField()


def check(request):
    if request.method == 'POST':
        try:
            data = json.loads(request.POST.get("response"))
            data = json_to_image(data)
        except Exception as e:
            return HttpResponse(f"Error loading the data,{e}")
        return HttpResponse(data, content_type="image/png")
    else:
        return render(request, 'index.html', {'form': front_end()})

startapp/templates/index.html
<!DOCTYPE html>
<html>

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <style>
        /* Create three equal columns that floats next to each other */
        @import url("https://fonts.googleapis.com/css?family=Nunito:400,600,700");

        .rainbow {
            background-color: #343a40;
            border-radius: 10px;
            color: #fff;
            cursor: pointer;
            padding: 8px 16px;
        }

        .rainbow-body {
            font-family: "Nunito", sans-serif;
            background-image: linear-gradient(to right,
                    #e7484f,
                    #f68b1d,
                    #fced00,
                    #009e4f,
                    #00aac3,
                    #732982);
            animation: slidebg 4s linear infinite;
        }

        /* @keyframes slidebg {
  to {
    background-position:20vw;
  }
} */

        .rainbow-5:hover {
            background-image: linear-gradient(to right,
                    #e7484f,
                    #e7484f 16.65%,
                    #f68b1d 16.65%,
                    #f68b1d 33.3%,
                    #fced00 33.3%,
                    #fced00 49.95%,
                    #009e4f 49.95%,
                    #009e4f 66.6%,
                    #00aac3 66.6%,
                    #00aac3 83.25%,
                    #732982 83.25%,
                    #732982 100%,
                    #e7484f 100%);
            animation: slidebg 2s linear infinite;
        }

        @keyframes slidebg {
            to {
                background-position: 20vw;
            }
        }
    </style>
    <script>
        function myFunction() {
            var x = document.getElementById("sampleImage");
            if (x.style.display === "none") {
                x.style.display = "block";
            } else {
                x.style.display = "none";
            }
        }
    </script>
</head>
<!-- <body style="background-color:black;color: ghostwhite;"> -->

<body class="rainbow-body">
    <h2 style="text-align: center">JSON TREE Visualizer</h2>

    <div class="container" style="text-align: center">
        <form action="" method="POST">
            {% csrf_token %}
            <textarea style="border-radius: 25px; padding: 20px" id="id_response" name="response" rows="50" cols="100">
    {"data":"Paste your JSON DATA HERE!"}</textarea>
            <div>
                <input class="rainbow rainbow-5" type="submit" value="LET'S FIRE IT!" />
            </div>
        </form>
        <button class="rainbow rainbow-5" onclick="myFunction()">
            View Sample JSON Visualizer
        </button>
        <div id="sampleImage" style="display: none">
            {% load static %}
            <img src="{% static 'download.png' %}" alt="My image" />
        </div>
        <footer>
            @develop by <a href="https://www.github.com/arunvemana">#arunvemana</a><br />
            @email at #arunvemana@outlook.com<br />
            @SourceCode
            <a href="https://github.com/arunvemana/jsontoimage">#here</a>
        </footer>
    </div>
</body>

</html>